using System;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;

namespace HolidayBooking.VacationService.Model
{
    public class Vacation
    {
        public enum VacationStatus
        {
            Pending,
            Approved,
            Declined,
            AwaitingFurtherDetails
        }
        public Vacation()
        {
        }

        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        // external ID or key, which may be easier to reference (ex: 1,2,3 etc.)
        public string Id { get; set; }

        public Guid EmployeeId { get; set; }
        public VacationPeriod VacationPeriod { get; set; }
        public VacationStatus Status { get; set; }
        public Guid ApprovedBy { get; set; }
        public DateTime ChangedOn { get; set; }

    }//class
}//ns
